# Generated by Django 3.2.3 on 2021-05-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('prioridade', models.IntegerField(default=1)),
                ('concluido', models.BooleanField(default=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
